# -*- coding: utf-8 -*-
#
# Copyright (c) 2010 Cidadanía Coop.
# Written by: Oscar Carballal Prego <info@oscarcp.com>
#
# This file is part of e-cidadania.
#
# e-cidadania is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# e-cidadania is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with e-cidadania. If not, see <http://www.gnu.org/licenses/>.

from django.forms import ModelForm, forms
from django.core import validators
from django.contrib.auth.models import User

from e_cidadania.apps.proposals.models import Proposal

class ProposalForm(ModelForm):

    """
    Autogenerated form for Proposal model.
    """
    class Meta:
        model = Proposal
        
class CustomProposal(ModelForm):
    
    """
    Proposal form for users.
    """
    title = forms.CharField(_('Title'), max_length=100, unique=True)
    message = forms.TextField(_('Message'), max_length=200)
    pub_date = forms.DateTimeField(auto_now_add=True)
    
    latitude = models.DecimalField(_('Latitude'), max_digits=8,
                                                  decimal_places=6)
    longitude = models.DecimalField(_('Longitude'), max_digits=8,
                                                    decimal_places=6)
