from bing import Bing
from google import Google
from googlev3 import GoogleV3
from dot_us import GeocoderDotUS
from geonames import GeoNames
from wiki_gis import MediaWiki
#from wiki_semantic import SemanticMediaWiki
from yahoo import Yahoo
from openmapquest import OpenMapQuest
from mapquest import MapQuest
